FROM python:3.8-slim

ENV PROJECT_LOCATION /srv/train
RUN mkdir -p $PROJECT_LOCATION
WORKDIR $PROJECT_LOCATION

RUN apt-get update -qq \
  && apt-get install --no-install-recommends -y \
    git

RUN pip install --no-cache-dir --upgrade poetry
RUN poetry config virtualenvs.create false
COPY train/pyproject.toml train/poetry.lock $PROJECT_LOCATION
RUN poetry install --no-dev

COPY train/train.py $PROJECT_LOCATION

ENTRYPOINT ["python", "train.py", "0.1", "0.1"]