apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    type: rest-api
spec:
  selector: 
    matchLabels:
      app: flask
  replicas: 3
  template:
    metadata:
      name: flask-tmpl
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: jommgoncalves/api:v1.0.0
          env:
          - name: MLFLOW_S3_ENDPOINT_URL
            value: http://minio-service:9000/
          - name: AWS_ACCESS_KEY_ID
            value: "minioadmin"
          - name: AWS_SECRET_ACCESS_KEY
            value: "minioadmin"
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000